### ISSUE TITLE
01.06.01 - Habit Title & Reason

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#10]
**Focus**
Habits

**Partial US**
As a doer, I want a habit title to be up to 20 characters and habit reason to be up to 30 characters.

**Reason**
Titles should be quite descriptive for niche habits, having a reason is important motivator.

**Story Points**
1

**Risk Level**
Low

**Comment by rmo1ualberta** [comment]
Finished as of #89
