### ISSUE TITLE
01.07.01 - Daily todo

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#11]
**Focus**
Habits

**Partial US**
As a doer, I want to see what habits I need to do today.

**Reason**
The core idea of the app is to help users create good habits, this means giving them a means of tracking which habits they need to execute _today_

**Story Points**
8

**Risk Level**
Medium

**Comment by rmo1ualberta** [comment]
Mostly finished as of #92; Bug fixes and some other things still need to be done.
