### ISSUE TITLE
01.08.01 - List user habits

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#12]
**Focus**
Habits

**Partial US**
As a doer, I want to see a list of all my habits.

**Reasoning**
Users need to be able to view, edit, delete existing habits as they see fit, easiest access point is by creating a list of habits all at once.

**Story Points**
3

**Risk Level**
Low

**Comment by rmo1ualberta** [comment]
Finished as of #89
