### ISSUE TITLE
02.01.01 - Habit Event Core

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#14]
**Focus**
Habit Events

**Partial US**
As a doer, I want to denote a habit event when I have done a habit as planned.

**Reason**
These instances help hold users accountable, and also act as a means of potentially making memories

**Story Points**
3

**Risk Level**
Low

**Comment by rmo1ualberta** [comment]
Finished as of #93
