### ISSUE TITLE
02.02.01 - Habit Event Comment

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#15]
**Focus**
Habit Events

**Partial US**
As a doer, I want a habit event to have an optional comment of up to 20 characters.

**Reasoning**
A comment makes the act of completing a habit successfully more valuable, the memory creation acts as a reward.

**Story Points**
1

**Risk Level**
Low

**Comment by rmo1ualberta** [comment]
Finished as of #93
