### ISSUE TITLE
02.03.01 - Optional Photograph

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#16]
**Focus**
Habit Events

**Partial US**
As a doer, I want a habit event to have an optional photograph to record what happened.

**Reason**
Again, adding a photo both acts as evidence but also a reward for successfully completing a habit, and helps keep the user accountable, in this way habits are better reinforced.

**Story Points**
3

**Risk Level**
Medium

**Comment by rmo1ualberta** [comment]
Finished as of #136
