### ISSUE TITLE
02.04.01 - Habit Event Details

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#17]
**Focus**
Habit Events

**Partial US**
As a doer, I want to view a given habit event and all its available details.

**Reason**
This allows users to reflect on what they did on a particular day in more detail than simply "Completed a habit"

**Story Points**
1

**Risk Level**
Low

**Comment by rmo1ualberta** [comment]
Finished as of #94
