### ISSUE TITLE
02.05.01 - Edit Habit Event

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#18]
**Focus**
Habit Events

**Partial US**
As a doer, I want to edit the details of a habit event of mine.

**Reason**
Users may mistakes, wish to update comments or photos.

**Story Points**
3

**Risk Level**
Medium

**Comment by rmo1ualberta** [comment]
Mostly finished as of #94; Need to add function for choosing image and using the built in camera, as well as implementing the ability to choose location.
