### ISSUE TITLE
02.06.01 - Delete Habit Event

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#19]
**Focus**
Habit Events

**Partial US**
As a doer, I want to delete a habit event of mine.

**Reason**
To account for potential mis-clicks, or if a user simply wants to delete a certain event.

**Story Points**
2

**Risk Level**
Medium

**Comment by rmo1ualberta** [comment]
Finished as of #92
