### ISSUE TITLE
05.01.01 - Following Doers

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#21]
**Focus**
Habit Following and Sharing

**Partial US**
As a doer, I want to ask another doer to follow all their public habits.

**Reason**
Socialization is a large aspect of the pressure to complete habits on time, and Doers want to view others successes!

**Story Points**
5

**Risk Level**
Medium

**Comment by Csongor-Szepesvari** [comment]
Risk Level should be adjusted to **Medium**

**Comment by rmo1ualberta** [comment]
Finished as of #137
