### ISSUE TITLE
05.03.01 - View others' habit lists

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#23]
**Focus**
Habit Following and Sharing

**Partial US**
As a doer, I want to view the public habits and visual indicators of the other doers I am granted to follow.

**Reason**
Doers need to be aware others can see their performance regarding their habits to motivate them to keep up.

**Story Points**
5

**Risk**
Medium

**Comment by rmo1ualberta** [comment]
Finished as of #137
