### ISSUE TITLE
06.01.01 - Locating Habit Events

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#24]
**Focus**
Geolocation and Maps

**Partial US**
As a doer, I want to a habit event to have an optional location to record where it happened.

**Reason**
Tagging where a doer completed an event both helps make memories by adding more specific details.

**Story Points**
5

**Risk Level**
Low

**Comment by rmo1ualberta** [comment]
Finished as of #156
