### ISSUE TITLE
US 01.01.01 - Habit description

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#5]
**Focus**
Habit

**Partial US**
As a doer, I want to add a habit, giving it a brief title, reason, and date to start.

**Reasoning**
Core idea for the app, must have habits to track and attempt to enforce

**Story Points**
2

**Risk Level**
Low

**Comment by rmo1ualberta** [comment]
Finished as of #89
