### ISSUE TITLE
US 01.02.01 - Days of Week

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#6]
**Focus**
Habits

**Partial US**
As a doer, I want a habit to have a plan for what days of the week it should regularly occur.

**Reasoning**
Schedules are very important for habits to form in the long run, and we need to be able to remind users to do their habits

**Story Points**
3

**Risk Level**
Moderate

**Comment by rmo1ualberta** [comment]
Finished as of #84
