### ISSUE TITLE
01.03.01 - View a habit

### ISSUE THREAD

**Issue by Csongor-Szepesvari** [CMPUT301F21T26/Habit-Tracker#7]
**Focus**
Habits

**Partial US**
As a doer, I want to view a given habit and its details.

**Reason**
Being able to view more detailed versions of habits will allow users to get a comprehensive idea of how they're doing with regards to their habits, and remind them of why they began them in the first place.

**Story Points**
1

**Risk Level**
Low

**Comment by rmo1ualberta** [comment]
Finished as of #89
